"""add role to students

Revision ID: 3ac8f59bc3d3
Revises: d36d68770fe5
Create Date: 2026-02-26 19:55:26.012192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac8f59bc3d3'
down_revision: Union[str, None] = 'd36d68770fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('role', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'role')
    # ### end Alembic commands ###
