"""initial

Revision ID: 643eec14bc69
Revises: 
Create Date: 2026-02-26 08:08:53.330803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643eec14bc69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('section', sa.String(length=255), nullable=False))
    op.add_column('lectures', sa.Column('section', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lectures', 'section')
    op.drop_column('exercises', 'section')
    # ### end Alembic commands ###
